# Generated by Django 4.0.2 on 2022-02-09 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 5, 8, 88829, tzinfo=utc)),
        ),
    ]
