# Generated by Django 4.0.2 on 2022-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('entries', '0006_client_user_alter_entry_client_alter_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(related_name='entries', to='tags.Tag'),
        ),
    ]
