# Generated by Django 4.0.2 on 2022-02-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_alter_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='entries/logos/'),
        ),
    ]
