# Generated by Django 4.0.2 on 2022-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entries/logos/'),
        ),
    ]
