# Generated by Django 4.0.2 on 2022-02-14 10:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_alter_client_logo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(check=models.Q(('end__gte', django.db.models.expressions.F('start'))), name='entries_entry_end_gte_start'),
        ),
    ]
