# Generated by Django 4.0.2 on 2022-02-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('entries', '0012_entry_entries_entry_end_gte_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='tags.Tag'),
        ),
    ]
