# Generated by Django 4.0.2 on 2022-02-14 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_remove_entry_entries_entry_end_gte_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 23, 12, 2, 592233)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 12, 2, 592255)),
        ),
    ]
