# Generated by Django 4.0.2 on 2022-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_entry_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='active',
        ),
        migrations.AddField(
            model_name='client',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
