# Generated by Django 4.0.2 on 2022-02-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_remove_client_active_remove_entry_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
