# Generated by Django 4.0.2 on 2022-12-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_organization_organizationaddress_organizationuser_and_more'),
        ('entries', '0024_entry_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.organization'),
        ),
    ]
