# Generated by Django 4.0.2 on 2023-02-22 10:09

from django.db import migrations, models
import django.db.models.deletion
import entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0025_client_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='general', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.client')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, entries.models.ChceckAgeMixin),
        ),
    ]
