# Generated by Django 4.0.2 on 2022-02-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_user_alter_entry_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
