# Generated by Django 4.0.2 on 2022-02-15 10:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_alter_entry_start_date_alter_entry_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
