# Generated by Django 4.0.2 on 2022-02-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_remove_entry_duration_remove_entry_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
