# Generated by Django 4.0.2 on 2022-02-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0023_remove_entry_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
