# Generated by Django 4.0.2 on 2023-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordercustomer_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='billing_cycle',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='billing_cycle_unit',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
