# Generated by Django 4.0.2 on 2023-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_billing_cycle_product_billing_cycle_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='active',
        ),
        migrations.AddField(
            model_name='order',
            name='last_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
