# Generated by Django 4.0.2 on 2023-04-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_paid_order_active_order_last_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(max_length=100)),
                ('paypal_name', models.CharField(max_length=255)),
                ('paypal_description', models.TextField(blank=True, null=True)),
                ('paypal_create_time', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_product', to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_plan', to='orders.product')),
            ],
        ),
    ]
