# Generated by Django 4.0.2 on 2023-04-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_paypalproduct_paypalplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_subscription', to='orders.paypalplan')),
            ],
        ),
    ]
